### ISSUE TITLE
Changing number of keypoints ?( pose_keypoint_coords[pose_count, :, :] = keypoint_coords ValueError: could not broadcast input array from shape (17,2) into shape (16,2))

### ISSUE THREAD

**Issue by basicvisual** [rwightman/posenet-python#10]
Hi , we know that posenet retruns 17 keypoints .I wanted to take the 2D detections and see what could be the effect of it when fed into a 3d lifting module.  For that reason , I had removed the nose keypoint which resutls in number of keypoints to be 16. The change was done in the `'constants.py'` file. However it lead to array mismatch  and I am trying to find what , causes this issue and possible fix.  The issue i get is 

`line 155, in decode_multiple_poses
    pose_keypoint_coords[pose_count, :, :] = keypoint_coords
ValueError: could not broadcast input array from shape (17,2) into shape (16,2)
`

I was wondering if there is a way to adpat the code ? Pointers and help would be appreciated. 

the file` constants.py`

```
`PART_NAMES = [
    "leftEye", "rightEye", "leftEar", "rightEar", "leftShoulder",
    "rightShoulder", "leftElbow", "rightElbow", "leftWrist", "rightWrist",
    "leftHip", "rightHip", "leftKnee", "rightKnee", "leftAnkle", "rightAnkle"
]

NUM_KEYPOINTS = len(PART_NAMES)

PART_IDS = {pn: pid for pid, pn in enumerate(PART_NAMES)}

CONNECTED_PART_NAMES = [
    ("leftHip", "leftShoulder"), ("leftElbow", "leftShoulder"),
    ("leftElbow", "leftWrist"), ("leftHip", "leftKnee"),
    ("leftKnee", "leftAnkle"), ("rightHip", "rightShoulder"),
    ("rightElbow", "rightShoulder"), ("rightElbow", "rightWrist"),
    ("rightHip", "rightKnee"), ("rightKnee", "rightAnkle"),
    ("leftShoulder", "rightShoulder"), ("leftHip", "rightHip")
]

CONNECTED_PART_INDICES = [(PART_IDS[a], PART_IDS[b]) for a, b in CONNECTED_PART_NAMES]

LOCAL_MAXIMUM_RADIUS = 1

POSE_CHAIN = [
    ("leftEye", "leftEar"), 
    ("rightEye", "rightEar"), ("leftShoulder", "leftElbow"), ("leftElbow", "leftWrist"),
    ("leftShoulder", "leftHip"), ("leftHip", "leftKnee"),
    ("leftKnee", "leftAnkle"), 
    ("rightShoulder", "rightElbow"), ("rightElbow", "rightWrist"),
    ("rightShoulder", "rightHip"), ("rightHip", "rightKnee"),
    ("rightKnee", "rightAnkle")
]

PARENT_CHILD_TUPLES = [(PART_IDS[parent], PART_IDS[child]) for parent, child in POSE_CHAIN]

PART_CHANNELS = [
  'left_face',
  'right_face',
  'right_upper_leg_front',
  'right_lower_leg_back',
  'right_upper_leg_back',
  'left_lower_leg_front',
  'left_upper_leg_front',
  'left_upper_leg_back',
  'left_lower_leg_back',
  'right_feet',
  'right_lower_leg_front',
  'left_feet',
  'torso_front',
  'torso_back',
  'right_upper_arm_front',
  'right_upper_arm_back',
  'right_lower_arm_back',
  'left_lower_arm_front',
  'left_upper_arm_front',
  'left_upper_arm_back',
  'left_lower_arm_back',
  'right_hand',
  'right_lower_arm_front',
  'left_hand'
]`
```

**Comment by rwightman** [comment]
@basicvisual don't mess around with the constants, removing the nose there will impact the pose chain, part positions are calculated with offsets based on their position relative to each other

if you want to remove parts, it's best to filter them out of the arrays returned by decode_multiple_poses based on the index of the parts you don't want.

**Comment by basicvisual** [comment]
Hi @rwightman , thanks for  the quick reply. I had been playing around a bit around the file  `decode_multi.py` as you had suggested. From what i understand ` pose_keypoint_coords  ` is an 3D array of dimensions`10x17x2` From what i understand the keypoints are arranged as follows 
```
x0,y0 --> nose 
x1,y1 --> left eye 
x2, y2 --> right eye 
......
.......
x16,y16 
```
Since i wanted to exclude the nose keypoint i modified the array as follows 
`pose_keypoint_coords_modified = np.delete(pose_keypoint_coords, 0, axis=1) ` which excludes  `x0,y0 (nose) keypoint . `

I tried to return the modified 16 keypoints instead of the original 17 keypoints intended. But it resulted in an error . 

```
s = np.sum((exist_pose_coords - keypoint_coords) ** 2, axis=2) > squared_nms_radius
ValueError: operands could not be broadcast together with shapes (1,16,2) (17,2) 
```
I was wondering , perhaps it is not wise to do the changes for the whole decode.py and instead , it is plausible that the 16 keypoints could be written to a json file per frame ?  

What do you think could be the best way forward ?

**Comment by basicvisual** [comment]
Hi Ross , @rwightman .  I have a question. 

- The `pose_keypoint_coords` is a `10x17x2 ` 3d matrix. I could manage to modify and filter out the 
   array by defining an array `pose_keypoint_coords_modifed` I trued to return the 
  `keypoints_coords_,modified ` but it returned an error 
 ```
   s = np.sum((exist_pose_coords - keypoint_coords) ** 2, axis=2) > squared_nms_radius
   ValueError: operands could not be broadcast together with shapes (1,16,2) (17,2) 
 ```
I guess i have to do , reshape it to a matrix `16x2` before retruning that in the fucntion. 

-  If i understand it correctly the keypoints currently arranged are in the order 
```
    x,0,y0 --> nose 
    x1,y1 ----> left eye
    x2,y2 ----> Right eye 
    ........
    x16,y16

```

-  In the file `webcam_demo.py`  The pose_decode function `posenet.decode_multi.decode_multiple_poses`  is executed per frame right ? Every frame in the video the `posenet` model  right ?  



`

-   Another question I have is , that if i want to , do modfications of  `keypoint_coords` , per frame. I can do perhaps something like 
   `keypoint_coords[frame_count]` 
and save it , to a file for each frame ?

**Comment by rwightman** [comment]
Best not to modify the arrays inside the decode_multiple_poses func, they are operated on in place... filter by applying a boolean mask or array of desired indices to the relevant index of each result array after they are returned from decode_multiple_poses

This is a frame based model yes, the model has no concept of time. You can do whatever you want with the results per frame, you'll quickly hit limits of python performance if you try to do extensive frame to frame processing/filtering or disk storage though.
