### ISSUE TITLE
possibility to save 2d skeleton as images ?

### ISSUE THREAD

**Issue by timtensor** [rwightman/posenet-python#16]
Hi 
As i understand, the current implementation returns a 2d skeleton per frame . Is it possible to save that image as `png` or `jpeg` in a folder ? if so , how can we do that ?

**Comment by MForMarlon** [comment]
Look here: https://github.com/rwightman/posenet-python/blob/master/image_demo.py#L54

Lines 54 through 58 save the image with the poses overlaid on the original image. The first argument in `cv2.imwrite()` is the path.
