### ISSUE TITLE
Introduce several images to improve performance

### ISSUE THREAD

**Issue by msanzn** [rwightman/posenet-python#17]
Is there any possibility of using the tf.stack function with several frames of the video to improve the performance as the GPU can process the images in parallel?

**Comment by rwightman** [comment]
It could be done, batching could definitely be added the the convnet easily. However, doing several images at once isn't very useful for the main use case of live/real-time video. Batching adds delay of one frame interval per batch element, it also makes the post-processing more bursty. The performance will suffer. It's only useful in the offline case, operating on lots of files or stored videos. EDIT or for multiple cameras, if you're careful with buffering, getting beyond a simple tech demo there...
