### ISSUE TITLE
How to custom train the model for another dataset

### ISSUE THREAD

**Issue by sivivicky** [rwightman/posenet-python#2]
I am wondering how to train the model with the dataset that I have? It would be really helpful if some procedure can be shared on training the model.

**Comment by rwightman** [comment]
There is no training code here. I had wanted to throw something in for that, but it's non-trivial and I've had other priorities. If I tackle it someday it'll likely be in the PyTorch version that I made.

The paper that Google's impl was based on is: https://arxiv.org/abs/1803.08225  ... you can get an idea of what training would involve from that

Microsoft released a recent human pose estimatgion model with training code: https://github.com/Microsoft/human-pose-estimation.pytorch ... based on their 'only tested with 4 P100 GPUs', it's likely a fair bit more resource intensive than these models. However, some ideas for training a smaller model could likely be gleaned from their code.
