### ISSUE TITLE
X and Y coordinates for the webcam_demo.py

### ISSUE THREAD

**Issue by karandish** [rwightman/posenet-python#21]
Hello, 
I'd like to know is there anyway that I can get the x-and y-coordinates and keypoint scores for the webcam? I noticed that we could get this information for the images, but not for the webcam. Could you please help and explain a bit about how I can get the coordinates and scores?
Thanks,

**Comment by rwightman** [comment]
It's a cut and paste from image demo to webcam. All that info is appropriately named arrays, also passed to the draw function in both cases. Spend some time exploring.
