### ISSUE TITLE
Theoretical way to increase speed for multi-pose decoding - pass tensors as references

### ISSUE THREAD

**Issue by oveddan** [rwightman/posenet-python#4]
Great job on this library!

I'm theorizing that you can get an increase in speed in the multi-pose decoding algorithm by passing the tensors as references and populating them, instead of creating and returning new ones in each frame.  I could be wrong but it would be worth giving this a shot.

**Comment by rwightman** [comment]
Thanks.

So move the arrays on lines 109-111 of decode_multi.py out to the client code? My hunch is it'll be a minimal gain but easy enough to try. I'll give it a shot sometime this week.

On my PyTorch version of this I achieved an extra 10-20fps (and much less CPU use) by keeping the part scoring on the GPU using max_pool and some other torch ops... I didn't want to fiddle with doing that in TF graph land so it's not in this port.

**Comment by rwightman** [comment]
Didn't appear to have a major impact. I'll leave as its own branch if you want to try.
