### ISSUE TITLE
CUDA and CuDNN version

### ISSUE THREAD

**Issue by BeatriceVince** [rwightman/posenet-python#5]
Thank you so much for your work!

I was wondering if you can tell us your environment configuration.
You mention, you used TensorFlow 1.12, but which version of CUDA and CuDNN library?

I am facing this problem:
```
Loaded runtime CuDNN library: 7402 (compatibility version 7400) but source was compiled with 7003 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2019-02-21 18:22:39.185823: F C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\kernels\conv_ops.cc:717] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
```

I have Windows 10, GPU INVIDIA GeForce 820M
I have installed TensorFlow 1.5
CUDA 9
CuDNN 7.4

Can you give me some suggestion how to fix the problem?
Thank you

**Comment by rwightman** [comment]
No idea on that specific error. I don't run Windows myself, just tested once on a machine that wasn't mine and also verified that someone else got this working on Windows as per the instructions. 

Note that as per the README, I used the conda version of tensorflow-gpu (1.12 at the time of testing) on both Windows and Linux and not use pip or any other distribution. The conda version includes CUDNN and CUDA libs, at the time of install I believe these would have been Cuda 9.2 and CUDNN 7.2.x.
