### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by ghost** [rwightman/posenet-python#6]
I am trying to implement a tracking function for the joint, to reduce the computation as it uses a tracker for the points an look for the movement only around the place it has been detected. It works as by detecting the whole frame each 10 frames and in the 9 in between it only tracks it with the correlation tracker in the dlib. The problem I have is that I have the points tracked it it appears that does not have the same position. Also it appears that because of the number of trackers it needs more computation than before (+200 in 30 frames). I do not know if you have another way of implementing it or accelerating the program. 

The code I have is:

```
import tensorflow as tf
import cv2
import time
import argparse
import dlib
import glob
import cvlib as cv
import threading
import time
import os 
import posenet

parser = argparse.ArgumentParser()
parser.add_argument('--model', type=int, default=101)
parser.add_argument('--cam_id', type=int, default=0)
parser.add_argument('--cam_width', type=int, default=1280)
parser.add_argument('--cam_height', type=int, default=720)
parser.add_argument('--scale_factor', type=float, default=0.7125)
args = parser.parse_args()

trackingQuality_threshold = 7
n_frames_to_detect = 10
min_confidence = 0.55
sec=5

def main():

    with tf.Session() as sess:
        model_cfg, model_outputs = posenet.load_model(args.model, sess)
        output_stride = model_cfg['output_stride']

        cap = cv2.VideoCapture("data/test_videos/dinner.mp4")
        cap.set(3, args.cam_width)
        cap.set(4, args.cam_height)
        len_video = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        fourcc = cv2.VideoWriter_fourcc(*'XVID')
        output_movie = cv2.VideoWriter('data/track_video/pose_detection.avi', fourcc, 29.97, (args.cam_width, args.cam_height))

        listofcenters = []
        centers = []
        max_displacement = []
        max_movement_single=[]

        frame_number = 0
        currentFaceID = 0
        cont=0

        rectangleColor = (0,0,255)
        faceTrackers = {}

        start = time.time()
        frame_count = 0
        while True:
            if frame_count==len_video:
                break

            input_image, display_image, output_scale = posenet.read_cap(
                cap, scale_factor=args.scale_factor, output_stride=output_stride)
            frame_count += 1

            fidsToDelete = []
            for fid in faceTrackers.keys():
                trackingQuality = faceTrackers[ fid ].update( overlay_image )

                if trackingQuality < trackingQuality_threshold:
                    fidsToDelete.append( fid )

            for fid in fidsToDelete:
                print("Removing fid " + str(fid) + " from list of trackers")
                faceTrackers.pop( fid , None )


            if (frame_number % n_frames_to_detect) == 0:

                heatmaps_result, offsets_result, displacement_fwd_result, displacement_bwd_result = sess.run(
                    model_outputs,
                    feed_dict={'image:0': input_image}
                )

                pose_scores, keypoint_scores, keypoint_coords = posenet.decode_multi.decode_multiple_poses( heatmaps_result.squeeze(axis=0), offsets_result.squeeze(axis=0), displacement_fwd_result.squeeze(axis=0), displacement_bwd_result.squeeze(axis=0), output_stride=output_stride, max_pose_detections=10, min_pose_score=0.15)

                keypoint_coords *= output_scale

                overlay_image = posenet.draw_skel_and_kp( display_image, pose_scores, keypoint_scores, keypoint_coords, min_pose_score=0.15, min_part_score=0.1)

                
                for idx,esq in enumerate(keypoint_coords):
                    for idx_2,coor in enumerate(esq):
                        x= int(coor[0])
                        y= int(coor[1])
                        w= 5
                        h= 5 
                        x_bar= x + 0.5 * w
                        y_bar= y + 0.5 * h

                        matchedFid = None
                    
                        for fid in faceTrackers.keys():
                            tracked_position = faceTrackers[fid].get_position()

                            t_x= int(tracked_position.left())
                            t_y= int(tracked_position.top())
                            t_w= int(tracked_position.width())
                            t_h= int(tracked_position.height())
                            t_x_bar= t_x + 0.5 * t_w
                            t_y_bar= t_y + 0.5 * t_h
    
                            if ( ( t_x <= x_bar   <= (t_x + t_w)) and 
                                 ( t_y <= y_bar   <= (t_y + t_h)) and 
                                 ( x   <= t_x_bar <= (x   + w  )) and 
                                 ( y   <= t_y_bar <= (y   + h  ))):

                                matchedFid = fid

                        if ((matchedFid is None)):

                            print("Creating new tracker " + str(currentFaceID))
                        
                            tracker = dlib.correlation_tracker()
                            tracker.start_track(overlay_image,dlib.rectangle( x-10,y-20,x+w+10,y+h+20))

                            faceTrackers[ currentFaceID ] = tracker
                            currentFaceID += 1


            for fid in faceTrackers.keys():
                tracked_position =  faceTrackers[fid].get_position()

                t_x = int(tracked_position.left())
                t_y = int(tracked_position.top())
                t_w = int(tracked_position.width())
                t_h = int(tracked_position.height())
                t_x_bar = t_x + 0.5 * t_w
                t_y_bar = t_y + 0.5 * t_h
                cv2.circle(overlay_image, (t_x, t_y),5, rectangleColor ,2)


            cv2.imshow('posenet', overlay_image)
            output_movie.write(overlay_image)
            
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

        print('Average FPS: ', frame_count / (time.time() - start))
        print('time: ', (time.time() - start))


if __name__ == "__main__":
    main()
```

**Comment by rwightman** [comment]
Tracking is definitely a worthwhile addition. These frame based pose algorithms suffer from frame to frame glitches and disappearance/reappearance of the parts or person that are quite noticeable for video sequences. Additionally there is no identifier for each detection that remains constant from frame to frame if you're doing analytics.

However, I don't see the value for saving compute. If you're running the base CNN on any sort of GPU I imagine it would be much faster than pixel based tracking algorithms running on a CPU. The forward pass through the CNN is 3-5ms on a decent GPU, faster than the Python post processing code for NMS and traversal of the parts for scoring. I can't see any pixel based tracking algorithm being better than that, it's likely several times worse. If you're running the NN on a CPU, there might be some benefit but seems like it'd be a wash.

**Comment by ghost** [comment]
Ok, thanks, but there are any way of knowing if the person has disapeared, I though of doing a general mean of all the points and track that one to know if the person is there or has moved, also I thought of doing the same for head, chest and arms. Does the point detection has any order, like head points, chest, arms and legs putting null in the ones not detected or if it does not detect the point it ignores having less positions. When I print the len of ach of the keypoint_coords I obtain always 17, but I do not know if the order is the same:
```
for coords in keypoint_coords:
    print(len(coords))


```

**Comment by rwightman** [comment]
For each pose (person), the parts are in the same order in the array and always the same size for performance. The score is used to evaluate whether each part is valid for each detection.

For the actual poses though, there is no consistent ordering from frame to frame in terms of which pose corresponds to which person you're hoping to track. The tracking algorithm needs to perform that matching reliably for the unique ids to work. I'd make sure your tracking bbox includes the whole person in each detection to provide enough features for the tracking detector to work. You'd also want to improve the matching of new CNN parts detection to existing tracking detections. Maybe calculate centroid distances or bbox overlap volumes and use greedy matching of smallest distance or biggest overlap vol.

You could search github and other places for solutions to the tracking part of the PostTrack (https://posetrack.net/leaderboard.php) challenge... see if you can find any code for the multi-frame part that would mesh well with these sorts of part detections.
