### ISSUE TITLE
Purpose of function "get_adjacent_keypoints"

### ISSUE THREAD

**Issue by gustavz** [rwightman/posenet-python#7]
what is the purpose of the function `get_adjacent_keypoints`?
Isn't this kind of redundant / unnecessary?

For my understanding inside `draw_sel_and_kp` it would be the same to just do the minimum score checking on the `instance_scores` followed by checking the `keypoint_scores` and then just draw each remaining keypoint and the lines defined in `CONNECTED_PART_INDICES`?

**Comment by rwightman** [comment]
It's building the list line segments for polylines to draw which are defined by connected part indices. The original algo specified that a skeleton segment is valid if both ends are above the min confidence.

I'm not sure how you'd get rid of it? You could try combining in it in the same loop as the keypoint scan but you'd need the connected parts in some sort of dict form and a bunch of dict lookups in the loop. Doubt it would be any faster. The connected parts data structure does not include all of the keypoints and some more than once, basically defines the skeleton segments with none of the face keypoints.

**Comment by gustavz** [comment]
I will write in in pseudo code because I implemented it in java and mapping it to your python implementation is too much work for now.
I have a pose class, containing an array of keypoints with x and y coordinates. Each pose has a score aswell as each keypoint, similar to the original implementation and should work aswell with your separate lists implementation.

```
for pose in poses:
  if pose.score > MIN_POSE_SCORE
    continue
  for id in FACE_IDS
    if pose.keypoint[id].score < MIN_PART_SCORE
      continue
    drawPoint(pose.keypoint[id].x, pose.keypoint[id].y)
  for parent,child in CONNECTED_PART_IDS
    if pose.keypoint[parent].score < MIN_PART_SCORE or pose.keypoint[child].score < MIN_PART_SCORE
      continue
    drawLine(pose.keypoint[parent].x, pose.keypoint[parent].y,pose.keypoint[child].x, pose.keypoint[child].y)
```

For my understanding this should work, without creating adjacent keypoint lists or anything, just reading out what's already in the detections.
This is of course not much faster but I always try to minimize code and functions overhead for readability.

**Comment by rwightman** [comment]
Yeah, looks fine aside from the '>' :) In Python I also wanted to draw the points for the non-face keypoints without making custom draw routines. Also, calling polylines once and drawKeypoints once as I did will likely save more than avoiding the extra work in get_adjacent_keypoints, but I haven't tested that theory.
