### ISSUE TITLE
Detection in low light and huge people density

### ISSUE THREAD

**Issue by ghost** [rwightman/posenet-python#8]
I am working in a project to detect the joints of people, but the conditions of the video are low light and with parts in which there are a high density of people. Going trough the code I realize that there are a variable "max_pose_detections" in the decode_multi to define the maximum number of people detected. There is a way of improving the detection of people to detect more, as changing the illumination or contrast of the image. I suppose that this problem can be partially solve using a training with data created and labeled to that case of use.

Also if there is a way of differentiating people very close from another, as when people are very close there a many times when it combines the points as it is one person.

**Comment by rwightman** [comment]
Google trained the network so you'd have to ask them. I did notice that performance falls off significantly with low dynamic range (noisy, low-light images). You can try to fiddle with the thresholds, filter the images, apply gain, etc. Overall though it's a performance optimized solution. Some of the other solutions with more capable models and tracking will likely handle more people and more adverse imaging conditions better but at the cost of much higher compute requirements. Good luck.
