### ISSUE TITLE
question on running the demo code 

### ISSUE THREAD

**Issue by basicvisual** [rwightman/posenet-python#9]
Hi , after installing different dependencies on ubuntu 16.04 , for your project . I come across this error . I am wondering if there is something i am missing in this regards ?? ? 
snippet below . I am however using virtual machine for ubuntu 

```
python webcam_demo.py 
2019-03-31 13:52:55.633518: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/ubuntu/repos/posenet-python/posenet/converter/config.py:9: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(cfg_f)
Cannot find model file ./_models/model-mobilenet_v1_101.pb, converting from tfjs...
Traceback (most recent call last):
  File "webcam_demo.py", line 63, in <module>
    main()
  File "webcam_demo.py", line 20, in main
    model_cfg, model_outputs = posenet.load_model(args.model, sess)
  File "/home/ubuntu/repos/posenet-python/posenet/model.py", line 42, in load_model
    convert(model_ord, model_dir, check=False)
  File "/home/ubuntu/repos/posenet-python/posenet/converter/tfjs2python.py", line 164, in convert
    variables = load_variables(chkpoint)
  File "/home/ubuntu/repos/posenet-python/posenet/converter/tfjs2python.py", line 60, in load_variables
    byte = open(os.path.join(base_dir, chkpoint, filename), 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_posenet_weights/mobilenet_v1_101/MobilenetV1_Conv2d_11_pointwise_biases'
```

**Comment by softwareeverything** [comment]
I'm using windows 10 and I'm getting same error how can I solve this?

**Comment by prashanthviswanatham** [comment]
> Hi , after installing different dependencies on ubuntu 16.04 , for your project . I come across this error . I am wondering if there is something i am missing in this regards ?? ?
> snippet below . I am however using virtual machine for ubuntu
> 
> ```
> python webcam_demo.py 
> 2019-03-31 13:52:55.633518: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> /home/ubuntu/repos/posenet-python/posenet/converter/config.py:9: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   cfg = yaml.load(cfg_f)
> Cannot find model file ./_models/model-mobilenet_v1_101.pb, converting from tfjs...
> Traceback (most recent call last):
>   File "webcam_demo.py", line 63, in <module>
>     main()
>   File "webcam_demo.py", line 20, in main
>     model_cfg, model_outputs = posenet.load_model(args.model, sess)
>   File "/home/ubuntu/repos/posenet-python/posenet/model.py", line 42, in load_model
>     convert(model_ord, model_dir, check=False)
>   File "/home/ubuntu/repos/posenet-python/posenet/converter/tfjs2python.py", line 164, in convert
>     variables = load_variables(chkpoint)
>   File "/home/ubuntu/repos/posenet-python/posenet/converter/tfjs2python.py", line 60, in load_variables
>     byte = open(os.path.join(base_dir, chkpoint, filename), 'rb').read()
> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_posenet_weights/mobilenet_v1_101/MobilenetV1_Conv2d_11_pointwise_biases'
> ```

I have the same issue anyone pls help
